/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "Bsp.h"
#include "timer.h"
#include "net.h"

#include "aurix_pin_mappings.h"
#include "boot_timer.h"
#include "boot_flow.h"
#include "boot_transport.h"




#define WAIT_6MS     6  //Wait time constant in milliseconds
#define WAIT_5MS     5   //Wait time constant in milliseconds

void Gpio_Init_PINs(void);
void Gpio_Power_On_Sequence121(void);

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;



void Gpio_Init_PINs(void)
{
    gpio_init_pins();

    IfxPort_setPinState(IFXCFG_PORT_MCU_LED_EN1.port, IFXCFG_PORT_MCU_LED_EN1.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_LED_EN2.port, IFXCFG_PORT_MCU_LED_EN2.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_EPHY_RST.port, IFXCFG_PORT_MCU_EPHY_RST.pinIndex, IfxPort_State_low);//PHY enable pin
}

void Gpio_Power_On_Sequence121(void)
{
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_6MS));    //Wait 6 milliseconds
    IfxPort_setPinState(IFXCFG_PORT_MCU_SW_LSCON.port, IFXCFG_PORT_MCU_SW_LSCON.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_SW_PWM.port, IFXCFG_PORT_MCU_SW_PWM.pinIndex, IfxPort_State_high);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_5MS));    //Wait 5 milliseconds
    IfxPort_setPinState(IFXCFG_PORT_MCU_SYS_5VS_EN.port, IFXCFG_PORT_MCU_SYS_5VS_EN.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_SYS_3V3S_EN.port, IFXCFG_PORT_MCU_SYS_3V3S_EN.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_ETH_3V3_EN.port, IFXCFG_PORT_MCU_ETH_3V3_EN.pinIndex, IfxPort_State_high);
    IfxPort_setPinState(IFXCFG_PORT_MCU_SYS_1V8S_EN.port, IFXCFG_PORT_MCU_SYS_1V8S_EN.pinIndex, IfxPort_State_high);
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    //Power on sequence
    Gpio_Init_PINs();
    Gpio_Power_On_Sequence121();
	DebugUart3_init();

    //Initial Timer
    Timer_Init(Time_1ms);

	while(1)
    {
      	/* service the watchdog */
		/* qqq none use now, keep for temp */
		//CopService();
		//wdt_kick(); 
		
		/* update the millisecond timer */
		TimerUpdate();

		Boot_Flow_Handler();
		if(flowCtrlFlag.bits.netTaskEnable){
			NetTask();
		}
    }
}


