/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC39XEDB
 * - package : LFBGA516
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P00_1_IO_CONFIG,
    IFXCFG_P00_2_IO_CONFIG,
    IFXCFG_P00_4_IO_CONFIG,
    IFXCFG_P00_5_IO_CONFIG,
    IFXCFG_P00_8_IO_CONFIG,
    IFXCFG_P00_9_IO_CONFIG,
    IFXCFG_P00_10_IO_CONFIG,
    IFXCFG_P00_11_IO_CONFIG,
    IFXCFG_P00_12_IO_CONFIG,
    IFXCFG_P00_13_IO_CONFIG,
    IFXCFG_P00_14_IO_CONFIG,
    IFXCFG_P00_15_IO_CONFIG,
    IFXCFG_P01_2_IO_CONFIG,
    IFXCFG_P01_3_IO_CONFIG,
    IFXCFG_P01_4_IO_CONFIG,
    IFXCFG_P01_5_IO_CONFIG,
    IFXCFG_P01_6_IO_CONFIG,
    IFXCFG_P01_7_IO_CONFIG,
    IFXCFG_P01_10_IO_CONFIG,
    IFXCFG_P01_11_IO_CONFIG,
    IFXCFG_P01_12_IO_CONFIG,
    IFXCFG_P01_14_IO_CONFIG,
    IFXCFG_P01_15_IO_CONFIG,
    IFXCFG_P02_4_IO_CONFIG,
    IFXCFG_P02_9_IO_CONFIG,
    IFXCFG_P02_10_IO_CONFIG,
    IFXCFG_P02_11_IO_CONFIG,
    IFXCFG_P02_12_IO_CONFIG,
    IFXCFG_P02_14_IO_CONFIG,
    IFXCFG_P10_0_IO_CONFIG,
    IFXCFG_P10_4_IO_CONFIG,
    IFXCFG_P10_7_IO_CONFIG,
    IFXCFG_P10_9_IO_CONFIG,
    IFXCFG_P10_10_IO_CONFIG,
    IFXCFG_P10_11_IO_CONFIG,
    IFXCFG_P10_13_IO_CONFIG,
    IFXCFG_P10_14_IO_CONFIG,
    IFXCFG_P10_15_IO_CONFIG,
    IFXCFG_P11_15_IO_CONFIG,
    IFXCFG_P13_0_IO_CONFIG,
    IFXCFG_P13_3_IO_CONFIG,
    IFXCFG_P13_5_IO_CONFIG,
    IFXCFG_P13_6_IO_CONFIG,
    IFXCFG_P13_7_IO_CONFIG,
    IFXCFG_P13_10_IO_CONFIG,
    IFXCFG_P13_14_IO_CONFIG,
    IFXCFG_P13_15_IO_CONFIG,
    IFXCFG_P14_11_IO_CONFIG,
    IFXCFG_P15_11_IO_CONFIG,
    IFXCFG_P15_13_IO_CONFIG,
    IFXCFG_P20_0_IO_CONFIG,
    IFXCFG_P20_1_IO_CONFIG,
    IFXCFG_P20_3_IO_CONFIG,
    IFXCFG_P21_2_IO_CONFIG,
    IFXCFG_P21_3_IO_CONFIG,
    IFXCFG_P22_1_IO_CONFIG,
    IFXCFG_P22_6_IO_CONFIG,
    IFXCFG_P22_7_IO_CONFIG,
    IFXCFG_P22_8_IO_CONFIG,
    IFXCFG_P23_1_IO_CONFIG,
    IFXCFG_P23_2_IO_CONFIG,
    IFXCFG_P24_2_IO_CONFIG,
    IFXCFG_P24_3_IO_CONFIG,
    IFXCFG_P24_4_IO_CONFIG,
    IFXCFG_P24_6_IO_CONFIG,
    IFXCFG_P24_7_IO_CONFIG,
    IFXCFG_P24_10_IO_CONFIG,
    IFXCFG_P24_12_IO_CONFIG,
    IFXCFG_P24_14_IO_CONFIG,
    IFXCFG_P24_15_IO_CONFIG,
    IFXCFG_P25_0_IO_CONFIG,
    IFXCFG_P25_1_IO_CONFIG,
    IFXCFG_P25_2_IO_CONFIG,
    IFXCFG_P25_3_IO_CONFIG,
    IFXCFG_P25_4_IO_CONFIG,
    IFXCFG_P25_5_IO_CONFIG,
    IFXCFG_P25_6_IO_CONFIG,
    IFXCFG_P25_7_IO_CONFIG,
    IFXCFG_P25_8_IO_CONFIG,
    IFXCFG_P25_9_IO_CONFIG,
    IFXCFG_P25_14_IO_CONFIG,
    IFXCFG_P26_0_IO_CONFIG,
    IFXCFG_P30_0_IO_CONFIG,
    IFXCFG_P30_2_IO_CONFIG,
    IFXCFG_P30_6_IO_CONFIG,
    IFXCFG_P30_11_IO_CONFIG,
    IFXCFG_P30_13_IO_CONFIG,
    IFXCFG_P31_0_IO_CONFIG,
    IFXCFG_P31_1_IO_CONFIG,
    IFXCFG_P31_2_IO_CONFIG,
    IFXCFG_P31_3_IO_CONFIG,
    IFXCFG_P31_4_IO_CONFIG,
    IFXCFG_P31_8_IO_CONFIG,
    IFXCFG_P31_9_IO_CONFIG,
    IFXCFG_P31_11_IO_CONFIG,
    IFXCFG_P31_13_IO_CONFIG,
    IFXCFG_P31_14_IO_CONFIG,
    IFXCFG_P31_15_IO_CONFIG,
    IFXCFG_P32_0_IO_CONFIG,
    IFXCFG_P32_1_IO_CONFIG,
    IFXCFG_P32_4_IO_CONFIG,
    IFXCFG_P32_5_IO_CONFIG,
    IFXCFG_P32_6_IO_CONFIG,
    IFXCFG_P33_2_IO_CONFIG,
    IFXCFG_P33_3_IO_CONFIG,
    IFXCFG_P33_8_IO_CONFIG,
    IFXCFG_P33_9_IO_CONFIG,
    IFXCFG_P34_3_IO_CONFIG,
    IFXCFG_P34_4_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}


/* ASCLIN0 pin configuration */

static const IfxPort_Io_ConfigPin asclin0_pin_table[] = 
{
    IFXCFG_P15_2_IO_CONFIG,
    IFXCFG_P33_10_IO_CONFIG
};

static const IfxPort_Io_Config asclin0_io_config_table = 
{
    sizeof(asclin0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin0_pin_table
};

extern void asclin0_init_pins(void)
{
    IfxPort_Io_initModule(&asclin0_io_config_table);
}


/* ASCLIN2 pin configuration */

static const IfxPort_Io_ConfigPin asclin2_pin_table[] = 
{
    IFXCFG_P02_0_IO_CONFIG,
    IFXCFG_P02_1_IO_CONFIG
};

static const IfxPort_Io_Config asclin2_io_config_table = 
{
    sizeof(asclin2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin2_pin_table
};

extern void asclin2_init_pins(void)
{
    IfxPort_Io_initModule(&asclin2_io_config_table);
}


/* ASCLIN3 pin configuration */

static const IfxPort_Io_ConfigPin asclin3_pin_table[] = 
{
    IFXCFG_P32_2_IO_CONFIG,
    IFXCFG_P32_3_IO_CONFIG
};

static const IfxPort_Io_Config asclin3_io_config_table = 
{
    sizeof(asclin3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin3_pin_table
};

extern void asclin3_init_pins(void)
{
    IfxPort_Io_initModule(&asclin3_io_config_table);
}


/* ASCLIN4 pin configuration */

static const IfxPort_Io_ConfigPin asclin4_pin_table[] = 
{
    IFXCFG_P22_9_IO_CONFIG,
    IFXCFG_P22_10_IO_CONFIG
};

static const IfxPort_Io_Config asclin4_io_config_table = 
{
    sizeof(asclin4_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin4_pin_table
};

extern void asclin4_init_pins(void)
{
    IfxPort_Io_initModule(&asclin4_io_config_table);
}


/* ASCLIN5 pin configuration */

static const IfxPort_Io_ConfigPin asclin5_pin_table[] = 
{
    IFXCFG_P00_6_IO_CONFIG,
    IFXCFG_P00_7_IO_CONFIG
};

static const IfxPort_Io_Config asclin5_io_config_table = 
{
    sizeof(asclin5_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin5_pin_table
};

extern void asclin5_init_pins(void)
{
    IfxPort_Io_initModule(&asclin5_io_config_table);
}


/* ASCLIN6 pin configuration */

static const IfxPort_Io_ConfigPin asclin6_pin_table[] = 
{
    IFXCFG_P01_0_IO_CONFIG,
    IFXCFG_P01_1_IO_CONFIG
};

static const IfxPort_Io_Config asclin6_io_config_table = 
{
    sizeof(asclin6_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin6_pin_table
};

extern void asclin6_init_pins(void)
{
    IfxPort_Io_initModule(&asclin6_io_config_table);
}


/* ASCLIN7 pin configuration */

static const IfxPort_Io_ConfigPin asclin7_pin_table[] = 
{
    IFXCFG_P01_9_IO_CONFIG,
    IFXCFG_P14_15_IO_CONFIG
};

static const IfxPort_Io_Config asclin7_io_config_table = 
{
    sizeof(asclin7_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin7_pin_table
};

extern void asclin7_init_pins(void)
{
    IfxPort_Io_initModule(&asclin7_io_config_table);
}


/* ASCLIN8 pin configuration */

static const IfxPort_Io_ConfigPin asclin8_pin_table[] = 
{
    IFXCFG_P33_6_IO_CONFIG,
    IFXCFG_P34_5_IO_CONFIG
};

static const IfxPort_Io_Config asclin8_io_config_table = 
{
    sizeof(asclin8_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin8_pin_table
};

extern void asclin8_init_pins(void)
{
    IfxPort_Io_initModule(&asclin8_io_config_table);
}


/* ASCLIN11 pin configuration */

static const IfxPort_Io_ConfigPin asclin11_pin_table[] = 
{
    IFXCFG_P21_0_IO_CONFIG,
    IFXCFG_P21_1_IO_CONFIG
};

static const IfxPort_Io_Config asclin11_io_config_table = 
{
    sizeof(asclin11_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin11_pin_table
};

extern void asclin11_init_pins(void)
{
    IfxPort_Io_initModule(&asclin11_io_config_table);
}


/* CAN0_NODE0 pin configuration */

static const IfxPort_Io_ConfigPin can0_node0_pin_table[] = 
{
    IFXCFG_P34_1_IO_CONFIG,
    IFXCFG_P34_2_IO_CONFIG
};

static const IfxPort_Io_Config can0_node0_io_config_table = 
{
    sizeof(can0_node0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node0_pin_table
};

extern void can0_node0_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node0_io_config_table);
}


/* CAN0_NODE1 pin configuration */

static const IfxPort_Io_ConfigPin can0_node1_pin_table[] = 
{
    IFXCFG_P14_0_IO_CONFIG,
    IFXCFG_P14_1_IO_CONFIG
};

static const IfxPort_Io_Config can0_node1_io_config_table = 
{
    sizeof(can0_node1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node1_pin_table
};

extern void can0_node1_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node1_io_config_table);
}


/* CAN0_NODE2 pin configuration */

static const IfxPort_Io_ConfigPin can0_node2_pin_table[] = 
{
    IFXCFG_P14_8_IO_CONFIG,
    IFXCFG_P15_0_IO_CONFIG
};

static const IfxPort_Io_Config can0_node2_io_config_table = 
{
    sizeof(can0_node2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node2_pin_table
};

extern void can0_node2_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node2_io_config_table);
}


/* CAN0_NODE3 pin configuration */

static const IfxPort_Io_ConfigPin can0_node3_pin_table[] = 
{
    IFXCFG_P20_9_IO_CONFIG,
    IFXCFG_P20_10_IO_CONFIG
};

static const IfxPort_Io_Config can0_node3_io_config_table = 
{
    sizeof(can0_node3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node3_pin_table
};

extern void can0_node3_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node3_io_config_table);
}


/* CAN1_NODE0 pin configuration */

static const IfxPort_Io_ConfigPin can1_node0_pin_table[] = 
{
    IFXCFG_P14_7_IO_CONFIG,
    IFXCFG_P14_9_IO_CONFIG
};

static const IfxPort_Io_Config can1_node0_io_config_table = 
{
    sizeof(can1_node0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can1_node0_pin_table
};

extern void can1_node0_init_pins(void)
{
    IfxPort_Io_initModule(&can1_node0_io_config_table);
}


/* CAN1_NODE1 pin configuration */

static const IfxPort_Io_ConfigPin can1_node1_pin_table[] = 
{
    IFXCFG_P23_6_IO_CONFIG,
    IFXCFG_P23_7_IO_CONFIG
};

static const IfxPort_Io_Config can1_node1_io_config_table = 
{
    sizeof(can1_node1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can1_node1_pin_table
};

extern void can1_node1_init_pins(void)
{
    IfxPort_Io_initModule(&can1_node1_io_config_table);
}


/* CAN1_NODE2 pin configuration */

static const IfxPort_Io_ConfigPin can1_node2_pin_table[] = 
{
    IFXCFG_P20_6_IO_CONFIG,
    IFXCFG_P20_7_IO_CONFIG
};

static const IfxPort_Io_Config can1_node2_io_config_table = 
{
    sizeof(can1_node2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can1_node2_pin_table
};

extern void can1_node2_init_pins(void)
{
    IfxPort_Io_initModule(&can1_node2_io_config_table);
}


/* CAN1_NODE3 pin configuration */

static const IfxPort_Io_ConfigPin can1_node3_pin_table[] = 
{
    IFXCFG_P22_4_IO_CONFIG,
    IFXCFG_P22_5_IO_CONFIG
};

static const IfxPort_Io_Config can1_node3_io_config_table = 
{
    sizeof(can1_node3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can1_node3_pin_table
};

extern void can1_node3_init_pins(void)
{
    IfxPort_Io_initModule(&can1_node3_io_config_table);
}


/* CAN2_NODE0 pin configuration */

static const IfxPort_Io_ConfigPin can2_node0_pin_table[] = 
{
    IFXCFG_P01_8_IO_CONFIG,
    IFXCFG_P01_13_IO_CONFIG
};

static const IfxPort_Io_Config can2_node0_io_config_table = 
{
    sizeof(can2_node0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can2_node0_pin_table
};

extern void can2_node0_init_pins(void)
{
    IfxPort_Io_initModule(&can2_node0_io_config_table);
}


/* CAN2_NODE1 pin configuration */

static const IfxPort_Io_ConfigPin can2_node1_pin_table[] = 
{
    IFXCFG_P13_9_IO_CONFIG,
    IFXCFG_P13_12_IO_CONFIG
};

static const IfxPort_Io_Config can2_node1_io_config_table = 
{
    sizeof(can2_node1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can2_node1_pin_table
};

extern void can2_node1_init_pins(void)
{
    IfxPort_Io_initModule(&can2_node1_io_config_table);
}


/* CAN2_NODE2 pin configuration */

static const IfxPort_Io_ConfigPin can2_node2_pin_table[] = 
{
    IFXCFG_P33_12_IO_CONFIG,
    IFXCFG_P33_13_IO_CONFIG
};

static const IfxPort_Io_Config can2_node2_io_config_table = 
{
    sizeof(can2_node2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can2_node2_pin_table
};

extern void can2_node2_init_pins(void)
{
    IfxPort_Io_initModule(&can2_node2_io_config_table);
}


/* CAN2_NODE3 pin configuration */

static const IfxPort_Io_ConfigPin can2_node3_pin_table[] = 
{
    IFXCFG_P13_4_IO_CONFIG,
    IFXCFG_P14_10_IO_CONFIG
};

static const IfxPort_Io_Config can2_node3_io_config_table = 
{
    sizeof(can2_node3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can2_node3_pin_table
};

extern void can2_node3_init_pins(void)
{
    IfxPort_Io_initModule(&can2_node3_io_config_table);
}


/* GPTONE0 pin configuration */

static const IfxPort_Io_ConfigPin gptone0_pin_table[] = 
{
    IFXCFG_P10_8_IO_CONFIG
};

static const IfxPort_Io_Config gptone0_io_config_table = 
{
    sizeof(gptone0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gptone0_pin_table
};

extern void gptone0_init_pins(void)
{
    IfxPort_Io_initModule(&gptone0_io_config_table);
}


/* I2C0 pin configuration */

static const IfxPort_Io_ConfigPin i2c0_pin_table[] = 
{
    IFXCFG_P13_1_IO_CONFIG,
    IFXCFG_P13_2_IO_CONFIG
};

static const IfxPort_Io_Config i2c0_io_config_table = 
{
    sizeof(i2c0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)i2c0_pin_table
};

extern void i2c0_init_pins(void)
{
    IfxPort_Io_initModule(&i2c0_io_config_table);
}


/* I2C1 pin configuration */

static const IfxPort_Io_ConfigPin i2c1_pin_table[] = 
{
    IFXCFG_P11_13_IO_CONFIG,
    IFXCFG_P11_14_IO_CONFIG
};

static const IfxPort_Io_Config i2c1_io_config_table = 
{
    sizeof(i2c1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)i2c1_pin_table
};

extern void i2c1_init_pins(void)
{
    IfxPort_Io_initModule(&i2c1_io_config_table);
}


/* JTAG pin configuration */

static const IfxPort_Io_ConfigPin jtag_pin_table[] = 
{
    IFXCFG_P21_6_IO_CONFIG,
    IFXCFG_P21_7_IO_CONFIG
};

static const IfxPort_Io_Config jtag_io_config_table = 
{
    sizeof(jtag_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)jtag_pin_table
};

extern void jtag_init_pins(void)
{
    IfxPort_Io_initModule(&jtag_io_config_table);
}


/* QSPI0_M pin configuration */

static const IfxPort_Io_ConfigPin qspi0_m_pin_table[] = 
{
    IFXCFG_P20_11_IO_CONFIG,
    IFXCFG_P20_12_IO_CONFIG,
    IFXCFG_P20_13_IO_CONFIG
};

static const IfxPort_Io_Config qspi0_m_io_config_table = 
{
    sizeof(qspi0_m_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi0_m_pin_table
};

extern void qspi0_m_init_pins(void)
{
    IfxPort_Io_initModule(&qspi0_m_io_config_table);
}


/* QSPI0_S pin configuration */

static const IfxPort_Io_ConfigPin qspi0_s_pin_table[] = 
{
    IFXCFG_P20_14_IO_CONFIG
};

static const IfxPort_Io_Config qspi0_s_io_config_table = 
{
    sizeof(qspi0_s_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi0_s_pin_table
};

extern void qspi0_s_init_pins(void)
{
    IfxPort_Io_initModule(&qspi0_s_io_config_table);
}


/* QSPI1_M pin configuration */

static const IfxPort_Io_ConfigPin qspi1_m_pin_table[] = 
{
    IFXCFG_P10_1_IO_CONFIG,
    IFXCFG_P10_3_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG
};

static const IfxPort_Io_Config qspi1_m_io_config_table = 
{
    sizeof(qspi1_m_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi1_m_pin_table
};

extern void qspi1_m_init_pins(void)
{
    IfxPort_Io_initModule(&qspi1_m_io_config_table);
}


/* QSPI1_S pin configuration */

static const IfxPort_Io_ConfigPin qspi1_s_pin_table[] = 
{
    IFXCFG_P10_2_IO_CONFIG
};

static const IfxPort_Io_Config qspi1_s_io_config_table = 
{
    sizeof(qspi1_s_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi1_s_pin_table
};

extern void qspi1_s_init_pins(void)
{
    IfxPort_Io_initModule(&qspi1_s_io_config_table);
}


/* QSPI2_M pin configuration */

static const IfxPort_Io_ConfigPin qspi2_m_pin_table[] = 
{
    IFXCFG_P15_1_IO_CONFIG,
    IFXCFG_P15_3_IO_CONFIG,
    IFXCFG_P15_4_IO_CONFIG,
    IFXCFG_P15_6_IO_CONFIG
};

static const IfxPort_Io_Config qspi2_m_io_config_table = 
{
    sizeof(qspi2_m_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi2_m_pin_table
};

extern void qspi2_m_init_pins(void)
{
    IfxPort_Io_initModule(&qspi2_m_io_config_table);
}


/* QSPI3_M pin configuration */

static const IfxPort_Io_ConfigPin qspi3_m_pin_table[] = 
{
    IFXCFG_P02_2_IO_CONFIG,
    IFXCFG_P02_3_IO_CONFIG,
    IFXCFG_P02_5_IO_CONFIG,
    IFXCFG_P02_6_IO_CONFIG,
    IFXCFG_P02_7_IO_CONFIG,
    IFXCFG_P02_8_IO_CONFIG,
    IFXCFG_P02_13_IO_CONFIG,
    IFXCFG_P02_15_IO_CONFIG
};

static const IfxPort_Io_Config qspi3_m_io_config_table = 
{
    sizeof(qspi3_m_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)qspi3_m_pin_table
};

extern void qspi3_m_init_pins(void)
{
    IfxPort_Io_initModule(&qspi3_m_io_config_table);
}


/* RGMII0 pin configuration */

static const IfxPort_Io_ConfigPin rgmii0_pin_table[] = 
{
    IFXCFG_P11_0_IO_CONFIG,
    IFXCFG_P11_1_IO_CONFIG,
    IFXCFG_P11_2_IO_CONFIG,
    IFXCFG_P11_3_IO_CONFIG,
    IFXCFG_P11_4_IO_CONFIG,
    IFXCFG_P11_5_IO_CONFIG,
    IFXCFG_P11_6_IO_CONFIG,
    IFXCFG_P11_7_IO_CONFIG,
    IFXCFG_P11_8_IO_CONFIG,
    IFXCFG_P11_9_IO_CONFIG,
    IFXCFG_P11_10_IO_CONFIG,
    IFXCFG_P11_11_IO_CONFIG,
    IFXCFG_P11_12_IO_CONFIG,
    IFXCFG_P12_0_IO_CONFIG,
    IFXCFG_P12_1_IO_CONFIG
};

static const IfxPort_Io_Config rgmii0_io_config_table = 
{
    sizeof(rgmii0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)rgmii0_pin_table
};

extern void rgmii0_init_pins(void)
{
    IfxPort_Io_initModule(&rgmii0_io_config_table);
}

