/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC39XEDB
 * - package : LFBGA516
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Symbolic names for GPIO ports */

// p00_0
#define IFXCFG_PORT_MCU_MUX_U38_EN              IfxPort_P00_0
#define IFXCFG_PORT_MCU_MUX_U38_EN_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U38_EN_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_1
#define IFXCFG_PORT_MCU_CAN11_EN                IfxPort_P00_1
#define IFXCFG_PORT_MCU_CAN11_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN11_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_2
#define IFXCFG_PORT_MCU_MUX_U38_A1              IfxPort_P00_2
#define IFXCFG_PORT_MCU_MUX_U38_A1_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U38_A1_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_4
#define IFXCFG_PORT_MCU_MUX_U38_A0              IfxPort_P00_4
#define IFXCFG_PORT_MCU_MUX_U38_A0_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U38_A0_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_5
#define IFXCFG_PORT_MCU_MUX_U1008_EN            IfxPort_P00_5
#define IFXCFG_PORT_MCU_MUX_U1008_EN_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1008_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_8
#define IFXCFG_PORT_MCU_CAN11_ERR               IfxPort_P00_8
#define IFXCFG_PORT_MCU_CAN11_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN11_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p00_9
#define IFXCFG_PORT_MCU_MUX_U1008_A1            IfxPort_P00_9
#define IFXCFG_PORT_MCU_MUX_U1008_A1_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1008_A1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_10
#define IFXCFG_PORT_MCU_MUX_U1008_A0            IfxPort_P00_10
#define IFXCFG_PORT_MCU_MUX_U1008_A0_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1008_A0_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_11
#define IFXCFG_PORT_MCU_MUX_U1009_EN            IfxPort_P00_11
#define IFXCFG_PORT_MCU_MUX_U1009_EN_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1009_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_12
#define IFXCFG_PORT_MCU_MUX_U1009_A1            IfxPort_P00_12
#define IFXCFG_PORT_MCU_MUX_U1009_A1_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1009_A1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_13
#define IFXCFG_PORT_MCU_MUX_U1009_A0            IfxPort_P00_13
#define IFXCFG_PORT_MCU_MUX_U1009_A0_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1009_A0_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_14
#define IFXCFG_PORT_MCU_MUX_U1010_EN            IfxPort_P00_14
#define IFXCFG_PORT_MCU_MUX_U1010_EN_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1010_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_15
#define IFXCFG_PORT_MCU_MUX_U1010_A1            IfxPort_P00_15
#define IFXCFG_PORT_MCU_MUX_U1010_A1_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1010_A1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_2
#define IFXCFG_PORT_MCU_MUX_U1010_A0            IfxPort_P01_2
#define IFXCFG_PORT_MCU_MUX_U1010_A0_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1010_A0_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_3
#define IFXCFG_PORT_MCU_CAN11_STB               IfxPort_P01_3
#define IFXCFG_PORT_MCU_CAN11_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN11_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_4
#define IFXCFG_PORT_SBW_INTLOCK11_SEL1          IfxPort_P01_4
#define IFXCFG_PORT_SBW_INTLOCK11_SEL1_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK11_SEL1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_5
#define IFXCFG_PORT_SBW_INTLOCK11_SEL2          IfxPort_P01_5
#define IFXCFG_PORT_SBW_INTLOCK11_SEL2_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK11_SEL2_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_6
#define IFXCFG_PORT_MCU_LIN7_SLP                IfxPort_P01_6
#define IFXCFG_PORT_MCU_LIN7_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN7_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_7
#define IFXCFG_PORT_MCU_LIN6_SLP                IfxPort_P01_7
#define IFXCFG_PORT_MCU_LIN6_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN6_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_10
#define IFXCFG_PORT_MCU_MUX_U1011_EN            IfxPort_P01_10
#define IFXCFG_PORT_MCU_MUX_U1011_EN_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1011_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_11
#define IFXCFG_PORT_MCU_MUX_U1011_A1            IfxPort_P01_11
#define IFXCFG_PORT_MCU_MUX_U1011_A1_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1011_A1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_12
#define IFXCFG_PORT_MCU_MUX_U1011_A0            IfxPort_P01_12
#define IFXCFG_PORT_MCU_MUX_U1011_A0_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_MUX_U1011_A0_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_14
#define IFXCFG_PORT_SBW_INTLOCK11_SEL3          IfxPort_P01_14
#define IFXCFG_PORT_SBW_INTLOCK11_SEL3_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK11_SEL3_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p01_15
#define IFXCFG_PORT_SBW_INTLOCK12_SEL1          IfxPort_P01_15
#define IFXCFG_PORT_SBW_INTLOCK12_SEL1_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK12_SEL1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_4
#define IFXCFG_PORT_SBW_INTLOCK12_SEL3          IfxPort_P02_4
#define IFXCFG_PORT_SBW_INTLOCK12_SEL3_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK12_SEL3_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_9
#define IFXCFG_PORT_BOX_INTLOCK11_SEL1          IfxPort_P02_9
#define IFXCFG_PORT_BOX_INTLOCK11_SEL1_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK11_SEL1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_10
#define IFXCFG_PORT_MCU_CHADEMO_CP1_EN          IfxPort_P02_10
#define IFXCFG_PORT_MCU_CHADEMO_CP1_EN_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CHADEMO_CP1_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_11
#define IFXCFG_PORT_MCU_CHADEMO_CP2_EN          IfxPort_P02_11
#define IFXCFG_PORT_MCU_CHADEMO_CP2_EN_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CHADEMO_CP2_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_12
#define IFXCFG_PORT_MCU_CHADEMO_CP3_EN          IfxPort_P02_12
#define IFXCFG_PORT_MCU_CHADEMO_CP3_EN_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CHADEMO_CP3_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_14
#define IFXCFG_PORT_MCU_CAN2_STB                IfxPort_P02_14
#define IFXCFG_PORT_MCU_CAN2_STB_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN2_STB_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_0
#define IFXCFG_PORT_BOX_INTLOCK11_SEL3          IfxPort_P10_0
#define IFXCFG_PORT_BOX_INTLOCK11_SEL3_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK11_SEL3_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_4
#define IFXCFG_PORT_BOX_INTLOCK12_SEL1          IfxPort_P10_4
#define IFXCFG_PORT_BOX_INTLOCK12_SEL1_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK12_SEL1_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_7
#define IFXCFG_PORT_BOX_INTLOCK12_SEL2          IfxPort_P10_7
#define IFXCFG_PORT_BOX_INTLOCK12_SEL2_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK12_SEL2_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_9
#define IFXCFG_PORT_BOX_INTLOCK12_SEL3          IfxPort_P10_9
#define IFXCFG_PORT_BOX_INTLOCK12_SEL3_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK12_SEL3_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_10
#define IFXCFG_PORT_SBW_INTLOCK12_SEL2          IfxPort_P10_10
#define IFXCFG_PORT_SBW_INTLOCK12_SEL2_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_SBW_INTLOCK12_SEL2_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_11
#define IFXCFG_PORT_BOX_INTLOCK11_SEL2          IfxPort_P10_11
#define IFXCFG_PORT_BOX_INTLOCK11_SEL2_MODE     IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BOX_INTLOCK11_SEL2_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_13
#define IFXCFG_PORT_MCU_CHADEMO_PP_EN           IfxPort_P10_13
#define IFXCFG_PORT_MCU_CHADEMO_PP_EN_MODE      IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CHADEMO_PP_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p10_14
#define IFXCFG_PORT_FAN1_SIGNAL_MCU             IfxPort_P10_14
#define IFXCFG_PORT_FAN1_SIGNAL_MCU_MODE        IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_FAN1_SIGNAL_MCU_PAD_DRIVER  IfxPort_PadDriver_cmosAutomotiveSpeed1

// p10_15
#define IFXCFG_PORT_MCU_PWM_FAN1                IfxPort_P10_15
#define IFXCFG_PORT_MCU_PWM_FAN1_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_PWM_FAN1_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p11_15
#define IFXCFG_PORT_MCU_EPHY_RST                IfxPort_P11_15
#define IFXCFG_PORT_MCU_EPHY_RST_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_EPHY_RST_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_0
#define IFXCFG_PORT_MCU_ETH_3V3_EN              IfxPort_P13_0
#define IFXCFG_PORT_MCU_ETH_3V3_EN_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_ETH_3V3_EN_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_3
#define IFXCFG_PORT_MCU_I2C_MUX_INT             IfxPort_P13_3
#define IFXCFG_PORT_MCU_I2C_MUX_INT_MODE        IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_I2C_MUX_INT_PAD_DRIVER  IfxPort_PadDriver_cmosAutomotiveSpeed1

// p13_5
#define IFXCFG_PORT_MCU_LIN2_SLP                IfxPort_P13_5
#define IFXCFG_PORT_MCU_LIN2_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN2_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_6
#define IFXCFG_PORT_MCU_CAN21_STB               IfxPort_P13_6
#define IFXCFG_PORT_MCU_CAN21_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN21_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_7
#define IFXCFG_PORT_MCU_LIN5_SLP                IfxPort_P13_7
#define IFXCFG_PORT_MCU_LIN5_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN5_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_10
#define IFXCFG_PORT_MCU_CAN21_EN                IfxPort_P13_10
#define IFXCFG_PORT_MCU_CAN21_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN21_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_14
#define IFXCFG_PORT_MCU_CAN21_ERR               IfxPort_P13_14
#define IFXCFG_PORT_MCU_CAN21_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN21_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p13_15
#define IFXCFG_PORT_MCU_CAN23_EN                IfxPort_P13_15
#define IFXCFG_PORT_MCU_CAN23_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN23_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p14_11
#define IFXCFG_PORT_MCU_CAN22_STB               IfxPort_P14_11
#define IFXCFG_PORT_MCU_CAN22_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN22_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_11
#define IFXCFG_PORT_MCU_CAN22_EN                IfxPort_P15_11
#define IFXCFG_PORT_MCU_CAN22_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN22_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_13
#define IFXCFG_PORT_MCU_CAN22_ERR               IfxPort_P15_13
#define IFXCFG_PORT_MCU_CAN22_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN22_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p20_0
#define IFXCFG_PORT_MCU_CAN12_EN                IfxPort_P20_0
#define IFXCFG_PORT_MCU_CAN12_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN12_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_1
#define IFXCFG_PORT_MCU_CAN1_EN                 IfxPort_P20_1
#define IFXCFG_PORT_MCU_CAN1_EN_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN1_EN_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_3
#define IFXCFG_PORT_SBC_VBST_PG_R               IfxPort_P20_3
#define IFXCFG_PORT_SBC_VBST_PG_R_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_SBC_VBST_PG_R_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p21_2
#define IFXCFG_PORT_SBC_ABE                     IfxPort_P21_2
#define IFXCFG_PORT_SBC_ABE_MODE                IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_SBC_ABE_PAD_DRIVER          IfxPort_PadDriver_cmosAutomotiveSpeed1

// p21_3
#define IFXCFG_PORT_MCU_CAN3_ERR                IfxPort_P21_3
#define IFXCFG_PORT_MCU_CAN3_ERR_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN3_ERR_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p22_1
#define IFXCFG_PORT_MCU_CAN23_STB               IfxPort_P22_1
#define IFXCFG_PORT_MCU_CAN23_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN23_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p22_6
#define IFXCFG_PORT_MCU_CAN12_ERR               IfxPort_P22_6
#define IFXCFG_PORT_MCU_CAN12_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN12_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p22_7
#define IFXCFG_PORT_MCU_LIN4_SLP                IfxPort_P22_7
#define IFXCFG_PORT_MCU_LIN4_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN4_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p22_8
#define IFXCFG_PORT_MCU_LIN11_SLP               IfxPort_P22_8
#define IFXCFG_PORT_MCU_LIN11_SLP_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN11_SLP_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p23_1
#define IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN      IfxPort_P23_1
#define IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN_MODE IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p23_2
#define IFXCFG_PORT_MCU_CAN1_ERR                IfxPort_P23_2
#define IFXCFG_PORT_MCU_CAN1_ERR_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN1_ERR_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p24_2
#define IFXCFG_PORT_MCU_CAN23_ERR               IfxPort_P24_2
#define IFXCFG_PORT_MCU_CAN23_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN23_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p24_3
#define IFXCFG_PORT_MCU_CAN1_STB                IfxPort_P24_3
#define IFXCFG_PORT_MCU_CAN1_STB_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN1_STB_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_4
#define IFXCFG_PORT_MCU_SYS_1V8S_EN             IfxPort_P24_4
#define IFXCFG_PORT_MCU_SYS_1V8S_EN_MODE        IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SYS_1V8S_EN_PAD_DRIVER  IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_6
#define IFXCFG_PORT_MCU_CAN10_STB               IfxPort_P24_6
#define IFXCFG_PORT_MCU_CAN10_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN10_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_7
#define IFXCFG_PORT_MCU_SYS_5VS_EN              IfxPort_P24_7
#define IFXCFG_PORT_MCU_SYS_5VS_EN_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SYS_5VS_EN_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_10
#define IFXCFG_PORT_MCU_SYS_3V3S_EN             IfxPort_P24_10
#define IFXCFG_PORT_MCU_SYS_3V3S_EN_MODE        IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SYS_3V3S_EN_PAD_DRIVER  IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_12
#define IFXCFG_PORT_MCU_CAN2_ERR                IfxPort_P24_12
#define IFXCFG_PORT_MCU_CAN2_ERR_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN2_ERR_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p24_14
#define IFXCFG_PORT_MCU_CAN12_STB               IfxPort_P24_14
#define IFXCFG_PORT_MCU_CAN12_STB_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN12_STB_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p24_15
#define IFXCFG_PORT_MCU_LED_EN1                 IfxPort_P24_15
#define IFXCFG_PORT_MCU_LED_EN1_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LED_EN1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_0
#define IFXCFG_PORT_MCU_LED_EN2                 IfxPort_P25_0
#define IFXCFG_PORT_MCU_LED_EN2_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LED_EN2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_1
#define IFXCFG_PORT_PIN_7_SEG_D1_D              IfxPort_P25_1
#define IFXCFG_PORT_PIN_7_SEG_D1_D_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_D_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_2
#define IFXCFG_PORT_PIN_7_SEG_D1_C              IfxPort_P25_2
#define IFXCFG_PORT_PIN_7_SEG_D1_C_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_C_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_3
#define IFXCFG_PORT_PIN_7_SEG_D1_E              IfxPort_P25_3
#define IFXCFG_PORT_PIN_7_SEG_D1_E_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_E_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_4
#define IFXCFG_PORT_PIN_7_SEG_D1_G              IfxPort_P25_4
#define IFXCFG_PORT_PIN_7_SEG_D1_G_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_G_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_5
#define IFXCFG_PORT_PIN_7_SEG_D1_F              IfxPort_P25_5
#define IFXCFG_PORT_PIN_7_SEG_D1_F_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_F_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_6
#define IFXCFG_PORT_TB_SW_VER_D0                IfxPort_P25_6
#define IFXCFG_PORT_TB_SW_VER_D0_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_TB_SW_VER_D0_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p25_7
#define IFXCFG_PORT_PIN_7_SEG_D1_B              IfxPort_P25_7
#define IFXCFG_PORT_PIN_7_SEG_D1_B_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_B_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_8
#define IFXCFG_PORT_PIN_7_SEG_D1_A              IfxPort_P25_8
#define IFXCFG_PORT_PIN_7_SEG_D1_A_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_A_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_9
#define IFXCFG_PORT_PIN_7_SEG_D1_DOT            IfxPort_P25_9
#define IFXCFG_PORT_PIN_7_SEG_D1_DOT_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D1_DOT_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p25_14
#define IFXCFG_PORT_MCU_CAN3_STB                IfxPort_P25_14
#define IFXCFG_PORT_MCU_CAN3_STB_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN3_STB_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p26_0
#define IFXCFG_PORT_TB_SW_VER_D1                IfxPort_P26_0
#define IFXCFG_PORT_TB_SW_VER_D1_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_TB_SW_VER_D1_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p30_0
#define IFXCFG_PORT_MCU_CAN1_EN_STATUS          IfxPort_P30_0
#define IFXCFG_PORT_MCU_CAN1_EN_STATUS_MODE     IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN1_EN_STATUS_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed1

// p30_2
#define IFXCFG_PORT_TB_SW_VER_D2                IfxPort_P30_2
#define IFXCFG_PORT_TB_SW_VER_D2_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_TB_SW_VER_D2_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p30_6
#define IFXCFG_PORT_TB_SW_VER_D3                IfxPort_P30_6
#define IFXCFG_PORT_TB_SW_VER_D3_MODE           IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_TB_SW_VER_D3_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed1

// p30_11
#define IFXCFG_PORT_MCU_CAN2_EN                 IfxPort_P30_11
#define IFXCFG_PORT_MCU_CAN2_EN_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN2_EN_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p30_13
#define IFXCFG_PORT_MCU_CAN3_EN                 IfxPort_P30_13
#define IFXCFG_PORT_MCU_CAN3_EN_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN3_EN_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_0
#define IFXCFG_PORT_PIN_7_SEG_D2_G              IfxPort_P31_0
#define IFXCFG_PORT_PIN_7_SEG_D2_G_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_G_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_1
#define IFXCFG_PORT_PIN_7_SEG_D2_F              IfxPort_P31_1
#define IFXCFG_PORT_PIN_7_SEG_D2_F_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_F_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_2
#define IFXCFG_PORT_PIN_7_SEG_D2_E              IfxPort_P31_2
#define IFXCFG_PORT_PIN_7_SEG_D2_E_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_E_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_3
#define IFXCFG_PORT_PIN_7_SEG_D2_C              IfxPort_P31_3
#define IFXCFG_PORT_PIN_7_SEG_D2_C_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_C_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_4
#define IFXCFG_PORT_PIN_7_SEG_D2_A              IfxPort_P31_4
#define IFXCFG_PORT_PIN_7_SEG_D2_A_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_A_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_8
#define IFXCFG_PORT_PIN_7_SEG_D2_DOT            IfxPort_P31_8
#define IFXCFG_PORT_PIN_7_SEG_D2_DOT_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_DOT_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_9
#define IFXCFG_PORT_PIN_7_SEG_D2_D              IfxPort_P31_9
#define IFXCFG_PORT_PIN_7_SEG_D2_D_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_D_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_11
#define IFXCFG_PORT_PIN_7_SEG_D2_B              IfxPort_P31_11
#define IFXCFG_PORT_PIN_7_SEG_D2_B_MODE         IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PIN_7_SEG_D2_B_PAD_DRIVER   IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_13
#define IFXCFG_PORT_MCU_CAN10_ERR               IfxPort_P31_13
#define IFXCFG_PORT_MCU_CAN10_ERR_MODE          IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CAN10_ERR_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed1

// p31_14
#define IFXCFG_PORT_MCU_CAN0_STB                IfxPort_P31_14
#define IFXCFG_PORT_MCU_CAN0_STB_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN0_STB_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p31_15
#define IFXCFG_PORT_MCU_CAN10_EN                IfxPort_P31_15
#define IFXCFG_PORT_MCU_CAN10_EN_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN10_EN_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p32_0
#define IFXCFG_PORT_MCU_SW_LSCON                IfxPort_P32_0
#define IFXCFG_PORT_MCU_SW_LSCON_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SW_LSCON_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p32_1
#define IFXCFG_PORT_MCU_SW_PWM                  IfxPort_P32_1
#define IFXCFG_PORT_MCU_SW_PWM_MODE             IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SW_PWM_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed4

// p32_4
#define IFXCFG_PORT_MCU_RCD_IN1                 IfxPort_P32_4
#define IFXCFG_PORT_MCU_RCD_IN1_MODE            IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_RCD_IN1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p32_5
#define IFXCFG_PORT_MCU_RCD_IN2                 IfxPort_P32_5
#define IFXCFG_PORT_MCU_RCD_IN2_MODE            IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_RCD_IN2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p32_6
#define IFXCFG_PORT_MCU_CP3_IN                  IfxPort_P32_6
#define IFXCFG_PORT_MCU_CP3_IN_MODE             IfxPort_Mode_inputNoPullDevice
#define IFXCFG_PORT_MCU_CP3_IN_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed1

// p33_2
#define IFXCFG_PORT_MCU_LIN0_SLP                IfxPort_P33_2
#define IFXCFG_PORT_MCU_LIN0_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN0_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_3
#define IFXCFG_PORT_MCU_LIN8_SLP                IfxPort_P33_3
#define IFXCFG_PORT_MCU_LIN8_SLP_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_LIN8_SLP_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_8
#define IFXCFG_PORT_MCU_ERR_SBC                 IfxPort_P33_8
#define IFXCFG_PORT_MCU_ERR_SBC_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_ERR_SBC_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_9
#define IFXCFG_PORT_MCU_WAKE_SBC                IfxPort_P33_9
#define IFXCFG_PORT_MCU_WAKE_SBC_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_WAKE_SBC_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4

// p34_3
#define IFXCFG_PORT_MCU_CAN0_EN                 IfxPort_P34_3
#define IFXCFG_PORT_MCU_CAN0_EN_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN0_EN_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p34_4
#define IFXCFG_PORT_MCU_CAN0_ERR                IfxPort_P34_4
#define IFXCFG_PORT_MCU_CAN0_ERR_MODE           IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_CAN0_ERR_PAD_DRIVER     IfxPort_PadDriver_cmosAutomotiveSpeed4


/* Generic port I/O configuration */

#define IFXCFG_P00_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U38_EN, IFXCFG_PORT_MCU_MUX_U38_EN_MODE, IFXCFG_PORT_MCU_MUX_U38_EN_PAD_DRIVER }
#define IFXCFG_P00_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN11_EN, IFXCFG_PORT_MCU_CAN11_EN_MODE, IFXCFG_PORT_MCU_CAN11_EN_PAD_DRIVER }
#define IFXCFG_P00_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U38_A1, IFXCFG_PORT_MCU_MUX_U38_A1_MODE, IFXCFG_PORT_MCU_MUX_U38_A1_PAD_DRIVER }
#define IFXCFG_P00_4_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U38_A0, IFXCFG_PORT_MCU_MUX_U38_A0_MODE, IFXCFG_PORT_MCU_MUX_U38_A0_PAD_DRIVER }
#define IFXCFG_P00_5_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U1008_EN, IFXCFG_PORT_MCU_MUX_U1008_EN_MODE, IFXCFG_PORT_MCU_MUX_U1008_EN_PAD_DRIVER }
#define IFXCFG_P00_8_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN11_ERR, IFXCFG_PORT_MCU_CAN11_ERR_MODE, IFXCFG_PORT_MCU_CAN11_ERR_PAD_DRIVER }
#define IFXCFG_P00_9_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U1008_A1, IFXCFG_PORT_MCU_MUX_U1008_A1_MODE, IFXCFG_PORT_MCU_MUX_U1008_A1_PAD_DRIVER }
#define IFXCFG_P00_10_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1008_A0, IFXCFG_PORT_MCU_MUX_U1008_A0_MODE, IFXCFG_PORT_MCU_MUX_U1008_A0_PAD_DRIVER }
#define IFXCFG_P00_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1009_EN, IFXCFG_PORT_MCU_MUX_U1009_EN_MODE, IFXCFG_PORT_MCU_MUX_U1009_EN_PAD_DRIVER }
#define IFXCFG_P00_12_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1009_A1, IFXCFG_PORT_MCU_MUX_U1009_A1_MODE, IFXCFG_PORT_MCU_MUX_U1009_A1_PAD_DRIVER }
#define IFXCFG_P00_13_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1009_A0, IFXCFG_PORT_MCU_MUX_U1009_A0_MODE, IFXCFG_PORT_MCU_MUX_U1009_A0_PAD_DRIVER }
#define IFXCFG_P00_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1010_EN, IFXCFG_PORT_MCU_MUX_U1010_EN_MODE, IFXCFG_PORT_MCU_MUX_U1010_EN_PAD_DRIVER }
#define IFXCFG_P00_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1010_A1, IFXCFG_PORT_MCU_MUX_U1010_A1_MODE, IFXCFG_PORT_MCU_MUX_U1010_A1_PAD_DRIVER }
#define IFXCFG_P01_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_MUX_U1010_A0, IFXCFG_PORT_MCU_MUX_U1010_A0_MODE, IFXCFG_PORT_MCU_MUX_U1010_A0_PAD_DRIVER }
#define IFXCFG_P01_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN11_STB, IFXCFG_PORT_MCU_CAN11_STB_MODE, IFXCFG_PORT_MCU_CAN11_STB_PAD_DRIVER }
#define IFXCFG_P01_4_IO_CONFIG                  { &IFXCFG_PORT_SBW_INTLOCK11_SEL1, IFXCFG_PORT_SBW_INTLOCK11_SEL1_MODE, IFXCFG_PORT_SBW_INTLOCK11_SEL1_PAD_DRIVER }
#define IFXCFG_P01_5_IO_CONFIG                  { &IFXCFG_PORT_SBW_INTLOCK11_SEL2, IFXCFG_PORT_SBW_INTLOCK11_SEL2_MODE, IFXCFG_PORT_SBW_INTLOCK11_SEL2_PAD_DRIVER }
#define IFXCFG_P01_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN7_SLP, IFXCFG_PORT_MCU_LIN7_SLP_MODE, IFXCFG_PORT_MCU_LIN7_SLP_PAD_DRIVER }
#define IFXCFG_P01_7_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN6_SLP, IFXCFG_PORT_MCU_LIN6_SLP_MODE, IFXCFG_PORT_MCU_LIN6_SLP_PAD_DRIVER }
#define IFXCFG_P01_10_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1011_EN, IFXCFG_PORT_MCU_MUX_U1011_EN_MODE, IFXCFG_PORT_MCU_MUX_U1011_EN_PAD_DRIVER }
#define IFXCFG_P01_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1011_A1, IFXCFG_PORT_MCU_MUX_U1011_A1_MODE, IFXCFG_PORT_MCU_MUX_U1011_A1_PAD_DRIVER }
#define IFXCFG_P01_12_IO_CONFIG                 { &IFXCFG_PORT_MCU_MUX_U1011_A0, IFXCFG_PORT_MCU_MUX_U1011_A0_MODE, IFXCFG_PORT_MCU_MUX_U1011_A0_PAD_DRIVER }
#define IFXCFG_P01_14_IO_CONFIG                 { &IFXCFG_PORT_SBW_INTLOCK11_SEL3, IFXCFG_PORT_SBW_INTLOCK11_SEL3_MODE, IFXCFG_PORT_SBW_INTLOCK11_SEL3_PAD_DRIVER }
#define IFXCFG_P01_15_IO_CONFIG                 { &IFXCFG_PORT_SBW_INTLOCK12_SEL1, IFXCFG_PORT_SBW_INTLOCK12_SEL1_MODE, IFXCFG_PORT_SBW_INTLOCK12_SEL1_PAD_DRIVER }
#define IFXCFG_P02_4_IO_CONFIG                  { &IFXCFG_PORT_SBW_INTLOCK12_SEL3, IFXCFG_PORT_SBW_INTLOCK12_SEL3_MODE, IFXCFG_PORT_SBW_INTLOCK12_SEL3_PAD_DRIVER }
#define IFXCFG_P02_9_IO_CONFIG                  { &IFXCFG_PORT_BOX_INTLOCK11_SEL1, IFXCFG_PORT_BOX_INTLOCK11_SEL1_MODE, IFXCFG_PORT_BOX_INTLOCK11_SEL1_PAD_DRIVER }
#define IFXCFG_P02_10_IO_CONFIG                 { &IFXCFG_PORT_MCU_CHADEMO_CP1_EN, IFXCFG_PORT_MCU_CHADEMO_CP1_EN_MODE, IFXCFG_PORT_MCU_CHADEMO_CP1_EN_PAD_DRIVER }
#define IFXCFG_P02_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_CHADEMO_CP2_EN, IFXCFG_PORT_MCU_CHADEMO_CP2_EN_MODE, IFXCFG_PORT_MCU_CHADEMO_CP2_EN_PAD_DRIVER }
#define IFXCFG_P02_12_IO_CONFIG                 { &IFXCFG_PORT_MCU_CHADEMO_CP3_EN, IFXCFG_PORT_MCU_CHADEMO_CP3_EN_MODE, IFXCFG_PORT_MCU_CHADEMO_CP3_EN_PAD_DRIVER }
#define IFXCFG_P02_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN2_STB, IFXCFG_PORT_MCU_CAN2_STB_MODE, IFXCFG_PORT_MCU_CAN2_STB_PAD_DRIVER }
#define IFXCFG_P10_0_IO_CONFIG                  { &IFXCFG_PORT_BOX_INTLOCK11_SEL3, IFXCFG_PORT_BOX_INTLOCK11_SEL3_MODE, IFXCFG_PORT_BOX_INTLOCK11_SEL3_PAD_DRIVER }
#define IFXCFG_P10_4_IO_CONFIG                  { &IFXCFG_PORT_BOX_INTLOCK12_SEL1, IFXCFG_PORT_BOX_INTLOCK12_SEL1_MODE, IFXCFG_PORT_BOX_INTLOCK12_SEL1_PAD_DRIVER }
#define IFXCFG_P10_7_IO_CONFIG                  { &IFXCFG_PORT_BOX_INTLOCK12_SEL2, IFXCFG_PORT_BOX_INTLOCK12_SEL2_MODE, IFXCFG_PORT_BOX_INTLOCK12_SEL2_PAD_DRIVER }
#define IFXCFG_P10_9_IO_CONFIG                  { &IFXCFG_PORT_BOX_INTLOCK12_SEL3, IFXCFG_PORT_BOX_INTLOCK12_SEL3_MODE, IFXCFG_PORT_BOX_INTLOCK12_SEL3_PAD_DRIVER }
#define IFXCFG_P10_10_IO_CONFIG                 { &IFXCFG_PORT_SBW_INTLOCK12_SEL2, IFXCFG_PORT_SBW_INTLOCK12_SEL2_MODE, IFXCFG_PORT_SBW_INTLOCK12_SEL2_PAD_DRIVER }
#define IFXCFG_P10_11_IO_CONFIG                 { &IFXCFG_PORT_BOX_INTLOCK11_SEL2, IFXCFG_PORT_BOX_INTLOCK11_SEL2_MODE, IFXCFG_PORT_BOX_INTLOCK11_SEL2_PAD_DRIVER }
#define IFXCFG_P10_13_IO_CONFIG                 { &IFXCFG_PORT_MCU_CHADEMO_PP_EN, IFXCFG_PORT_MCU_CHADEMO_PP_EN_MODE, IFXCFG_PORT_MCU_CHADEMO_PP_EN_PAD_DRIVER }
#define IFXCFG_P10_14_IO_CONFIG                 { &IFXCFG_PORT_FAN1_SIGNAL_MCU, IFXCFG_PORT_FAN1_SIGNAL_MCU_MODE, IFXCFG_PORT_FAN1_SIGNAL_MCU_PAD_DRIVER }
#define IFXCFG_P10_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_PWM_FAN1, IFXCFG_PORT_MCU_PWM_FAN1_MODE, IFXCFG_PORT_MCU_PWM_FAN1_PAD_DRIVER }
#define IFXCFG_P11_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_EPHY_RST, IFXCFG_PORT_MCU_EPHY_RST_MODE, IFXCFG_PORT_MCU_EPHY_RST_PAD_DRIVER }
#define IFXCFG_P13_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_ETH_3V3_EN, IFXCFG_PORT_MCU_ETH_3V3_EN_MODE, IFXCFG_PORT_MCU_ETH_3V3_EN_PAD_DRIVER }
#define IFXCFG_P13_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_I2C_MUX_INT, IFXCFG_PORT_MCU_I2C_MUX_INT_MODE, IFXCFG_PORT_MCU_I2C_MUX_INT_PAD_DRIVER }
#define IFXCFG_P13_5_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN2_SLP, IFXCFG_PORT_MCU_LIN2_SLP_MODE, IFXCFG_PORT_MCU_LIN2_SLP_PAD_DRIVER }
#define IFXCFG_P13_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN21_STB, IFXCFG_PORT_MCU_CAN21_STB_MODE, IFXCFG_PORT_MCU_CAN21_STB_PAD_DRIVER }
#define IFXCFG_P13_7_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN5_SLP, IFXCFG_PORT_MCU_LIN5_SLP_MODE, IFXCFG_PORT_MCU_LIN5_SLP_PAD_DRIVER }
#define IFXCFG_P13_10_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN21_EN, IFXCFG_PORT_MCU_CAN21_EN_MODE, IFXCFG_PORT_MCU_CAN21_EN_PAD_DRIVER }
#define IFXCFG_P13_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN21_ERR, IFXCFG_PORT_MCU_CAN21_ERR_MODE, IFXCFG_PORT_MCU_CAN21_ERR_PAD_DRIVER }
#define IFXCFG_P13_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN23_EN, IFXCFG_PORT_MCU_CAN23_EN_MODE, IFXCFG_PORT_MCU_CAN23_EN_PAD_DRIVER }
#define IFXCFG_P14_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN22_STB, IFXCFG_PORT_MCU_CAN22_STB_MODE, IFXCFG_PORT_MCU_CAN22_STB_PAD_DRIVER }
#define IFXCFG_P15_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN22_EN, IFXCFG_PORT_MCU_CAN22_EN_MODE, IFXCFG_PORT_MCU_CAN22_EN_PAD_DRIVER }
#define IFXCFG_P15_13_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN22_ERR, IFXCFG_PORT_MCU_CAN22_ERR_MODE, IFXCFG_PORT_MCU_CAN22_ERR_PAD_DRIVER }
#define IFXCFG_P20_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN12_EN, IFXCFG_PORT_MCU_CAN12_EN_MODE, IFXCFG_PORT_MCU_CAN12_EN_PAD_DRIVER }
#define IFXCFG_P20_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN1_EN, IFXCFG_PORT_MCU_CAN1_EN_MODE, IFXCFG_PORT_MCU_CAN1_EN_PAD_DRIVER }
#define IFXCFG_P20_3_IO_CONFIG                  { &IFXCFG_PORT_SBC_VBST_PG_R, IFXCFG_PORT_SBC_VBST_PG_R_MODE, IFXCFG_PORT_SBC_VBST_PG_R_PAD_DRIVER }
#define IFXCFG_P21_2_IO_CONFIG                  { &IFXCFG_PORT_SBC_ABE, IFXCFG_PORT_SBC_ABE_MODE, IFXCFG_PORT_SBC_ABE_PAD_DRIVER }
#define IFXCFG_P21_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN3_ERR, IFXCFG_PORT_MCU_CAN3_ERR_MODE, IFXCFG_PORT_MCU_CAN3_ERR_PAD_DRIVER }
#define IFXCFG_P22_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN23_STB, IFXCFG_PORT_MCU_CAN23_STB_MODE, IFXCFG_PORT_MCU_CAN23_STB_PAD_DRIVER }
#define IFXCFG_P22_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN12_ERR, IFXCFG_PORT_MCU_CAN12_ERR_MODE, IFXCFG_PORT_MCU_CAN12_ERR_PAD_DRIVER }
#define IFXCFG_P22_7_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN4_SLP, IFXCFG_PORT_MCU_LIN4_SLP_MODE, IFXCFG_PORT_MCU_LIN4_SLP_PAD_DRIVER }
#define IFXCFG_P22_8_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN11_SLP, IFXCFG_PORT_MCU_LIN11_SLP_MODE, IFXCFG_PORT_MCU_LIN11_SLP_PAD_DRIVER }
#define IFXCFG_P23_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN, IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN_MODE, IFXCFG_PORT_MCU_RST_AIRPRESSURE_EN_PAD_DRIVER }
#define IFXCFG_P23_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN1_ERR, IFXCFG_PORT_MCU_CAN1_ERR_MODE, IFXCFG_PORT_MCU_CAN1_ERR_PAD_DRIVER }
#define IFXCFG_P24_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN23_ERR, IFXCFG_PORT_MCU_CAN23_ERR_MODE, IFXCFG_PORT_MCU_CAN23_ERR_PAD_DRIVER }
#define IFXCFG_P24_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN1_STB, IFXCFG_PORT_MCU_CAN1_STB_MODE, IFXCFG_PORT_MCU_CAN1_STB_PAD_DRIVER }
#define IFXCFG_P24_4_IO_CONFIG                  { &IFXCFG_PORT_MCU_SYS_1V8S_EN, IFXCFG_PORT_MCU_SYS_1V8S_EN_MODE, IFXCFG_PORT_MCU_SYS_1V8S_EN_PAD_DRIVER }
#define IFXCFG_P24_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN10_STB, IFXCFG_PORT_MCU_CAN10_STB_MODE, IFXCFG_PORT_MCU_CAN10_STB_PAD_DRIVER }
#define IFXCFG_P24_7_IO_CONFIG                  { &IFXCFG_PORT_MCU_SYS_5VS_EN, IFXCFG_PORT_MCU_SYS_5VS_EN_MODE, IFXCFG_PORT_MCU_SYS_5VS_EN_PAD_DRIVER }
#define IFXCFG_P24_10_IO_CONFIG                 { &IFXCFG_PORT_MCU_SYS_3V3S_EN, IFXCFG_PORT_MCU_SYS_3V3S_EN_MODE, IFXCFG_PORT_MCU_SYS_3V3S_EN_PAD_DRIVER }
#define IFXCFG_P24_12_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN2_ERR, IFXCFG_PORT_MCU_CAN2_ERR_MODE, IFXCFG_PORT_MCU_CAN2_ERR_PAD_DRIVER }
#define IFXCFG_P24_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN12_STB, IFXCFG_PORT_MCU_CAN12_STB_MODE, IFXCFG_PORT_MCU_CAN12_STB_PAD_DRIVER }
#define IFXCFG_P24_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_LED_EN1, IFXCFG_PORT_MCU_LED_EN1_MODE, IFXCFG_PORT_MCU_LED_EN1_PAD_DRIVER }
#define IFXCFG_P25_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_LED_EN2, IFXCFG_PORT_MCU_LED_EN2_MODE, IFXCFG_PORT_MCU_LED_EN2_PAD_DRIVER }
#define IFXCFG_P25_1_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_D, IFXCFG_PORT_PIN_7_SEG_D1_D_MODE, IFXCFG_PORT_PIN_7_SEG_D1_D_PAD_DRIVER }
#define IFXCFG_P25_2_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_C, IFXCFG_PORT_PIN_7_SEG_D1_C_MODE, IFXCFG_PORT_PIN_7_SEG_D1_C_PAD_DRIVER }
#define IFXCFG_P25_3_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_E, IFXCFG_PORT_PIN_7_SEG_D1_E_MODE, IFXCFG_PORT_PIN_7_SEG_D1_E_PAD_DRIVER }
#define IFXCFG_P25_4_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_G, IFXCFG_PORT_PIN_7_SEG_D1_G_MODE, IFXCFG_PORT_PIN_7_SEG_D1_G_PAD_DRIVER }
#define IFXCFG_P25_5_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_F, IFXCFG_PORT_PIN_7_SEG_D1_F_MODE, IFXCFG_PORT_PIN_7_SEG_D1_F_PAD_DRIVER }
#define IFXCFG_P25_6_IO_CONFIG                  { &IFXCFG_PORT_TB_SW_VER_D0, IFXCFG_PORT_TB_SW_VER_D0_MODE, IFXCFG_PORT_TB_SW_VER_D0_PAD_DRIVER }
#define IFXCFG_P25_7_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_B, IFXCFG_PORT_PIN_7_SEG_D1_B_MODE, IFXCFG_PORT_PIN_7_SEG_D1_B_PAD_DRIVER }
#define IFXCFG_P25_8_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_A, IFXCFG_PORT_PIN_7_SEG_D1_A_MODE, IFXCFG_PORT_PIN_7_SEG_D1_A_PAD_DRIVER }
#define IFXCFG_P25_9_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D1_DOT, IFXCFG_PORT_PIN_7_SEG_D1_DOT_MODE, IFXCFG_PORT_PIN_7_SEG_D1_DOT_PAD_DRIVER }
#define IFXCFG_P25_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN3_STB, IFXCFG_PORT_MCU_CAN3_STB_MODE, IFXCFG_PORT_MCU_CAN3_STB_PAD_DRIVER }
#define IFXCFG_P26_0_IO_CONFIG                  { &IFXCFG_PORT_TB_SW_VER_D1, IFXCFG_PORT_TB_SW_VER_D1_MODE, IFXCFG_PORT_TB_SW_VER_D1_PAD_DRIVER }
#define IFXCFG_P30_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN1_EN_STATUS, IFXCFG_PORT_MCU_CAN1_EN_STATUS_MODE, IFXCFG_PORT_MCU_CAN1_EN_STATUS_PAD_DRIVER }
#define IFXCFG_P30_2_IO_CONFIG                  { &IFXCFG_PORT_TB_SW_VER_D2, IFXCFG_PORT_TB_SW_VER_D2_MODE, IFXCFG_PORT_TB_SW_VER_D2_PAD_DRIVER }
#define IFXCFG_P30_6_IO_CONFIG                  { &IFXCFG_PORT_TB_SW_VER_D3, IFXCFG_PORT_TB_SW_VER_D3_MODE, IFXCFG_PORT_TB_SW_VER_D3_PAD_DRIVER }
#define IFXCFG_P30_11_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN2_EN, IFXCFG_PORT_MCU_CAN2_EN_MODE, IFXCFG_PORT_MCU_CAN2_EN_PAD_DRIVER }
#define IFXCFG_P30_13_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN3_EN, IFXCFG_PORT_MCU_CAN3_EN_MODE, IFXCFG_PORT_MCU_CAN3_EN_PAD_DRIVER }
#define IFXCFG_P31_0_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_G, IFXCFG_PORT_PIN_7_SEG_D2_G_MODE, IFXCFG_PORT_PIN_7_SEG_D2_G_PAD_DRIVER }
#define IFXCFG_P31_1_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_F, IFXCFG_PORT_PIN_7_SEG_D2_F_MODE, IFXCFG_PORT_PIN_7_SEG_D2_F_PAD_DRIVER }
#define IFXCFG_P31_2_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_E, IFXCFG_PORT_PIN_7_SEG_D2_E_MODE, IFXCFG_PORT_PIN_7_SEG_D2_E_PAD_DRIVER }
#define IFXCFG_P31_3_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_C, IFXCFG_PORT_PIN_7_SEG_D2_C_MODE, IFXCFG_PORT_PIN_7_SEG_D2_C_PAD_DRIVER }
#define IFXCFG_P31_4_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_A, IFXCFG_PORT_PIN_7_SEG_D2_A_MODE, IFXCFG_PORT_PIN_7_SEG_D2_A_PAD_DRIVER }
#define IFXCFG_P31_8_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_DOT, IFXCFG_PORT_PIN_7_SEG_D2_DOT_MODE, IFXCFG_PORT_PIN_7_SEG_D2_DOT_PAD_DRIVER }
#define IFXCFG_P31_9_IO_CONFIG                  { &IFXCFG_PORT_PIN_7_SEG_D2_D, IFXCFG_PORT_PIN_7_SEG_D2_D_MODE, IFXCFG_PORT_PIN_7_SEG_D2_D_PAD_DRIVER }
#define IFXCFG_P31_11_IO_CONFIG                 { &IFXCFG_PORT_PIN_7_SEG_D2_B, IFXCFG_PORT_PIN_7_SEG_D2_B_MODE, IFXCFG_PORT_PIN_7_SEG_D2_B_PAD_DRIVER }
#define IFXCFG_P31_13_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN10_ERR, IFXCFG_PORT_MCU_CAN10_ERR_MODE, IFXCFG_PORT_MCU_CAN10_ERR_PAD_DRIVER }
#define IFXCFG_P31_14_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN0_STB, IFXCFG_PORT_MCU_CAN0_STB_MODE, IFXCFG_PORT_MCU_CAN0_STB_PAD_DRIVER }
#define IFXCFG_P31_15_IO_CONFIG                 { &IFXCFG_PORT_MCU_CAN10_EN, IFXCFG_PORT_MCU_CAN10_EN_MODE, IFXCFG_PORT_MCU_CAN10_EN_PAD_DRIVER }
#define IFXCFG_P32_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_SW_LSCON, IFXCFG_PORT_MCU_SW_LSCON_MODE, IFXCFG_PORT_MCU_SW_LSCON_PAD_DRIVER }
#define IFXCFG_P32_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_SW_PWM, IFXCFG_PORT_MCU_SW_PWM_MODE, IFXCFG_PORT_MCU_SW_PWM_PAD_DRIVER }
#define IFXCFG_P32_4_IO_CONFIG                  { &IFXCFG_PORT_MCU_RCD_IN1, IFXCFG_PORT_MCU_RCD_IN1_MODE, IFXCFG_PORT_MCU_RCD_IN1_PAD_DRIVER }
#define IFXCFG_P32_5_IO_CONFIG                  { &IFXCFG_PORT_MCU_RCD_IN2, IFXCFG_PORT_MCU_RCD_IN2_MODE, IFXCFG_PORT_MCU_RCD_IN2_PAD_DRIVER }
#define IFXCFG_P32_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_CP3_IN, IFXCFG_PORT_MCU_CP3_IN_MODE, IFXCFG_PORT_MCU_CP3_IN_PAD_DRIVER }
#define IFXCFG_P33_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN0_SLP, IFXCFG_PORT_MCU_LIN0_SLP_MODE, IFXCFG_PORT_MCU_LIN0_SLP_PAD_DRIVER }
#define IFXCFG_P33_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_LIN8_SLP, IFXCFG_PORT_MCU_LIN8_SLP_MODE, IFXCFG_PORT_MCU_LIN8_SLP_PAD_DRIVER }
#define IFXCFG_P33_8_IO_CONFIG                  { &IFXCFG_PORT_MCU_ERR_SBC, IFXCFG_PORT_MCU_ERR_SBC_MODE, IFXCFG_PORT_MCU_ERR_SBC_PAD_DRIVER }
#define IFXCFG_P33_9_IO_CONFIG                  { &IFXCFG_PORT_MCU_WAKE_SBC, IFXCFG_PORT_MCU_WAKE_SBC_MODE, IFXCFG_PORT_MCU_WAKE_SBC_PAD_DRIVER }
#define IFXCFG_P34_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN0_EN, IFXCFG_PORT_MCU_CAN0_EN_MODE, IFXCFG_PORT_MCU_CAN0_EN_PAD_DRIVER }
#define IFXCFG_P34_4_IO_CONFIG                  { &IFXCFG_PORT_MCU_CAN0_ERR, IFXCFG_PORT_MCU_CAN0_ERR_MODE, IFXCFG_PORT_MCU_CAN0_ERR_PAD_DRIVER }


/* Generic alternate I/O configuration */

// asclin0
#define IFXCFG_P15_2_IO_CONFIG                  { &IfxPort_P15_2, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P33_10_IO_CONFIG                 { &IfxPort_P33_10, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// asclin2
#define IFXCFG_P02_0_IO_CONFIG                  { &IfxPort_P02_0, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_1_IO_CONFIG                  { &IfxPort_P02_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// asclin3
#define IFXCFG_P32_2_IO_CONFIG                  { &IfxPort_P32_2, IfxPort_Mode_inputPullDown, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P32_3_IO_CONFIG                  { &IfxPort_P32_3, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// asclin4
#define IFXCFG_P22_9_IO_CONFIG                  { &IfxPort_P22_9, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P22_10_IO_CONFIG                 { &IfxPort_P22_10, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// asclin5
#define IFXCFG_P00_6_IO_CONFIG                  { &IfxPort_P00_6, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P00_7_IO_CONFIG                  { &IfxPort_P00_7, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// asclin6
#define IFXCFG_P01_0_IO_CONFIG                  { &IfxPort_P01_0, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P01_1_IO_CONFIG                  { &IfxPort_P01_1, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// asclin7
#define IFXCFG_P01_9_IO_CONFIG                  { &IfxPort_P01_9, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P14_15_IO_CONFIG                 { &IfxPort_P14_15, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// asclin8
#define IFXCFG_P33_6_IO_CONFIG                  { &IfxPort_P33_6, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P34_5_IO_CONFIG                  { &IfxPort_P34_5, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// asclin11
#define IFXCFG_P21_0_IO_CONFIG                  { &IfxPort_P21_0, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P21_1_IO_CONFIG                  { &IfxPort_P21_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can0_node0
#define IFXCFG_P34_1_IO_CONFIG                  { &IfxPort_P34_1, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P34_2_IO_CONFIG                  { &IfxPort_P34_2, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can0_node1
#define IFXCFG_P14_0_IO_CONFIG                  { &IfxPort_P14_0, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P14_1_IO_CONFIG                  { &IfxPort_P14_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can0_node2
#define IFXCFG_P14_8_IO_CONFIG                  { &IfxPort_P14_8, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P15_0_IO_CONFIG                  { &IfxPort_P15_0, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// can0_node3
#define IFXCFG_P20_9_IO_CONFIG                  { &IfxPort_P20_9, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P20_10_IO_CONFIG                 { &IfxPort_P20_10, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// can1_node0
#define IFXCFG_P14_7_IO_CONFIG                  { &IfxPort_P14_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P14_9_IO_CONFIG                  { &IfxPort_P14_9, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// can1_node1
#define IFXCFG_P23_6_IO_CONFIG                  { &IfxPort_P23_6, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P23_7_IO_CONFIG                  { &IfxPort_P23_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can1_node2
#define IFXCFG_P20_6_IO_CONFIG                  { &IfxPort_P20_6, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P20_7_IO_CONFIG                  { &IfxPort_P20_7, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// can1_node3
#define IFXCFG_P22_4_IO_CONFIG                  { &IfxPort_P22_4, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P22_5_IO_CONFIG                  { &IfxPort_P22_5, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can2_node0
#define IFXCFG_P01_8_IO_CONFIG                  { &IfxPort_P01_8, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P01_13_IO_CONFIG                 { &IfxPort_P01_13, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// can2_node1
#define IFXCFG_P13_9_IO_CONFIG                  { &IfxPort_P13_9, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P13_12_IO_CONFIG                 { &IfxPort_P13_12, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can2_node2
#define IFXCFG_P33_12_IO_CONFIG                 { &IfxPort_P33_12, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P33_13_IO_CONFIG                 { &IfxPort_P33_13, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// can2_node3
#define IFXCFG_P13_4_IO_CONFIG                  { &IfxPort_P13_4, IfxPort_Mode_outputPushPullAlt7, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P14_10_IO_CONFIG                 { &IfxPort_P14_10, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// gptone0
#define IFXCFG_P10_8_IO_CONFIG                  { &IfxPort_P10_8, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// i2c0
#define IFXCFG_P13_1_IO_CONFIG                  { &IfxPort_P13_1, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P13_1_IO_CONFIG_IN               { &IfxPort_P13_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P13_2_IO_CONFIG                  { &IfxPort_P13_2, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P13_2_IO_CONFIG_IN               { &IfxPort_P13_2, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// i2c1
#define IFXCFG_P11_13_IO_CONFIG                 { &IfxPort_P11_13, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_13_IO_CONFIG_IN              { &IfxPort_P11_13, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_14_IO_CONFIG                 { &IfxPort_P11_14, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_14_IO_CONFIG_IN              { &IfxPort_P11_14, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// jtag
#define IFXCFG_P21_6_IO_CONFIG                  { &IfxPort_P21_6, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P21_7_IO_CONFIG                  { &IfxPort_P21_7, IfxPort_Mode_outputPushPullGeneral, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// qspi0_m
#define IFXCFG_P20_11_IO_CONFIG                 { &IfxPort_P20_11, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P20_12_IO_CONFIG                 { &IfxPort_P20_12, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P20_13_IO_CONFIG                 { &IfxPort_P20_13, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// qspi0_s
#define IFXCFG_P20_14_IO_CONFIG                 { &IfxPort_P20_14, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// qspi1_m
#define IFXCFG_P10_1_IO_CONFIG                  { &IfxPort_P10_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P10_3_IO_CONFIG                  { &IfxPort_P10_3, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P20_8_IO_CONFIG                  { &IfxPort_P20_8, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// qspi1_s
#define IFXCFG_P10_2_IO_CONFIG                  { &IfxPort_P10_2, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// qspi2_m
#define IFXCFG_P15_1_IO_CONFIG                  { &IfxPort_P15_1, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P15_3_IO_CONFIG                  { &IfxPort_P15_3, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P15_4_IO_CONFIG                  { &IfxPort_P15_4, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P15_6_IO_CONFIG                  { &IfxPort_P15_6, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// qspi3_m
#define IFXCFG_P02_2_IO_CONFIG                  { &IfxPort_P02_2, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_3_IO_CONFIG                  { &IfxPort_P02_3, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_5_IO_CONFIG                  { &IfxPort_P02_5, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P02_6_IO_CONFIG                  { &IfxPort_P02_6, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_7_IO_CONFIG                  { &IfxPort_P02_7, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_8_IO_CONFIG                  { &IfxPort_P02_8, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_13_IO_CONFIG                 { &IfxPort_P02_13, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P02_15_IO_CONFIG                 { &IfxPort_P02_15, IfxPort_Mode_outputPushPullAlt2, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// rgmii0
#define IFXCFG_P11_0_IO_CONFIG                  { &IfxPort_P11_0, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_1_IO_CONFIG                  { &IfxPort_P11_1, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_2_IO_CONFIG                  { &IfxPort_P11_2, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_3_IO_CONFIG                  { &IfxPort_P11_3, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_4_IO_CONFIG                  { &IfxPort_P11_4, IfxPort_Mode_outputPushPullAlt7, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_5_IO_CONFIG                  { &IfxPort_P11_5, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_6_IO_CONFIG                  { &IfxPort_P11_6, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P11_7_IO_CONFIG                  { &IfxPort_P11_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_8_IO_CONFIG                  { &IfxPort_P11_8, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_9_IO_CONFIG                  { &IfxPort_P11_9, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_10_IO_CONFIG                 { &IfxPort_P11_10, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_11_IO_CONFIG                 { &IfxPort_P11_11, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P11_12_IO_CONFIG                 { &IfxPort_P11_12, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P12_0_IO_CONFIG                  { &IfxPort_P12_0, IfxPort_Mode_outputPushPullAlt6, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P12_1_IO_CONFIG                  { &IfxPort_P12_1, IfxPort_Mode_outputPushPullGeneral, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P12_1_IO_CONFIG_IN               { &IfxPort_P12_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed4 }


/* Initialization routines */

extern void gpio_init_pins(void);

extern void asclin0_init_pins(void);

extern void asclin2_init_pins(void);

extern void asclin3_init_pins(void);

extern void asclin4_init_pins(void);

extern void asclin5_init_pins(void);

extern void asclin6_init_pins(void);

extern void asclin7_init_pins(void);

extern void asclin8_init_pins(void);

extern void asclin11_init_pins(void);

extern void can0_node0_init_pins(void);

extern void can0_node1_init_pins(void);

extern void can0_node2_init_pins(void);

extern void can0_node3_init_pins(void);

extern void can1_node0_init_pins(void);

extern void can1_node1_init_pins(void);

extern void can1_node2_init_pins(void);

extern void can1_node3_init_pins(void);

extern void can2_node0_init_pins(void);

extern void can2_node1_init_pins(void);

extern void can2_node2_init_pins(void);

extern void can2_node3_init_pins(void);

extern void gptone0_init_pins(void);

extern void i2c0_init_pins(void);

extern void i2c1_init_pins(void);

extern void jtag_init_pins(void);

extern void qspi0_m_init_pins(void);

extern void qspi0_s_init_pins(void);

extern void qspi1_m_init_pins(void);

extern void qspi1_s_init_pins(void);

extern void qspi2_m_init_pins(void);

extern void qspi3_m_init_pins(void);

extern void rgmii0_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
